apiVersion: apps/v1
kind: Deployment
metadata:
  name: publications-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: publication_dockerized
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
